spring.application.name=pawfinder
spring.datasource.url:jdbc:mysql://localhost:3306/pawfinder?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
spring.datasource.username: root
spring.datasource.password: Adidas17#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
spring.thymeleaf.cache: false
# Cloudinary configuration
cloudinary.cloud-name=dvss9jivl
cloudinary.api-key=353157668784825
cloudinary.api-secret=PPNNWCm3gS09sXEpGZ8jpcDKJME
# Multipart file upload configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# JWT configuration
jwt.secret=eG94Y3B2RkZxY3h0R0ttbHppT2V4anp3dmtzSk1XQ0E1SHU0c2p6Z2xPZkVzY2g3